@isTest
public class MyHelloWorld2Test {
    /*static testMethod void validateMyHelloWorld2() {
        Movie__c m = new Movie__c(Name='Harry Potter 2', Price__c = 100);
        System.debug('Precio inicial de venta: ' + m.Price__c);

        insert m;

        m = [SELECT New_Price__c FROM Movie__c WHERE Id =:m.Id];
        System.debug('Precio con descuento : ' + m.New_Price__c);

        System.assertEquals(99, m.New_Price__c);
    }*/
}